# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemiRestfulUsers', '0002_auto_20170921_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
